export const siteConfig = {
  title: 'Moshood Oluwadamilare | Front-end developer',
  description:
    "Hello, I'm Oluwadamilare. I am front-end developer from Poland. I enjoy building sites and apps. My focus is React (Next.js).",
  keywords: [
    'Moshood Oluwadamilare',
    'Front-end developer',
    'Lagos, Nigeria',
    'React',
    'Next.js',
    'Web development',
    'Front-end',
    'UI/UX',
    'Responsive design',
    'JavaScript',
    'HTML',
    'CSS',
    'Portfolio',
    'Projects',
    'Website',
    'Web applications',
    'Developer',
    'Code',
    'Programming',
    'Tech enthusiast',
  ],
};
